### ISSUE TITLE
USER STORY: Manage Contents (Admin)

### ISSUE THREAD

**Issue by BeckySkel** [BeckySkel/fullstack-project-4#1]
As an **admin**, I can **edit and remove recipes** so that **I can manage the site contents**.

---
#### Acceptance Criteria
**1.** Recipes can be viewed, edited and removed via the admin panel
**2.** Removing a recipe hides it, but doesn't delete it
**3.** A 'removal reason' input is present
**4.** 404 page displays when trying to access removed recipes
**5.** User is alerted when recipe is removed/edited, with 'reason' displayed

---
#### Tasks
- [x] Create Recipe data model
- [x] Create superuser to access admin panel
- [x] Add search box and filter to admin panel
- [x] Add removal action
- [x] Redirect to 404 if trying to access removed recipe
- [x] Create alert
