### ISSUE TITLE
USER STORY: Search for Recipes (User)

### ISSUE THREAD

**Issue by BeckySkel** [BeckySkel/fullstack-project-4#10]
As a **recipe viewer**, I can **search for recipes** so that **I can find one that  matches what I'm looking for**.

---
#### Acceptance Criteria
**1.** All users can use search bar to find public recipes, logged-in or out
**2.** Displays recipes with matching key words on submission
**3.** Users can search for ingredients, title and tags
**4.** Displays message if no results found

---
#### Tasks
- [x] Add search bar to header
- [x] Create template to display search results
- [x] Create 'no results found' template
