### ISSUE TITLE
USER STORY: Recipe Tags (User)

### ISSUE THREAD

**Issue by BeckySkel** [BeckySkel/fullstack-project-4#12]
As a **recipe sharer**, I can **add tags to my recipes** so that **they are more visible to others**.

---
#### Acceptance Criteria
**1.** Included in the add and edit recipe forms
**2.** User can browse by tags
**3.** Select from predetermined tags, not user created
**4.** Searchable in search bar

---
#### Tasks
- [x] Create tags (10 - 15 options)
- [x] Add 'Tags' input to add/edit recipe form
- [x] Add tags to Recipes data model
- [x] Add dropdown list to navbar and link to tag views
- [x ] Add tags to search
