### ISSUE TITLE
USER STORY: Nutritional Info (User)

### ISSUE THREAD

**Issue by BeckySkel** [BeckySkel/fullstack-project-4#13]
As a **recipe viewer**, I can **view the nutritional information of a recipe** so that **I can make an informed decision based on my dietary needs**.

---
#### Acceptance Criteria
**1.** Calculated from ingredients and amount
**2.** Calories displayed on recipe card
**3.** Full nutritional info displayed in table on recipe page 

---
#### Tasks
- [ ] Link calories/nutrition API
- [ ] Split 'ingredients' input into 'ingredient' and 'amount'
- [ ] Create code to calculate calories and other info based on ingredients and amount
