### ISSUE TITLE
USER STORY: Recipe Difficulty (User)

### ISSUE THREAD

**Issue by BeckySkel** [BeckySkel/fullstack-project-4#14]
As a **recipe viewer**, I can **view the recipe difficulty** so that **I can select a recipe which would suit my skill set**.

---
#### Acceptance Criteria
**1.** Recipe sharer sets difficulty in add/edit recipe form
**2.** Options are: Beginner, Intermediate, Advanced
**3.** Difficulty is displayed on card and page

---
#### Tasks
- [ ] Add 'Difficulty' input on add/edit recipe form
- [ ] Add to data model
- [ ] Edit views to display difficulty
