### ISSUE TITLE
USER STORY: Manage Comments (Admin)

### ISSUE THREAD

**Issue by BeckySkel** [BeckySkel/fullstack-project-4#2]
As an **admin**, I can **read and remove comments** so that **inappropriate comments can be removed**.

---
#### Acceptance Criteria
**1.** Comments can be viewed and removed via the admin panel
**2.** A 'reason' input is present
**3.** User is alerted when comment is removed, with 'reason' displayed

---
#### Tasks
- [x] Create User and Comment data models
- [x] Add search box to models in admin panel
- [x] Create alert and style with CSS
