### ISSUE TITLE
USER STORY: Post Recipes (User)

### ISSUE THREAD

**Issue by BeckySkel** [BeckySkel/fullstack-project-4#3]
As a **recipe sharer**, I can **post my own recipes** so that **I can share them with others**.

---
#### Acceptance Criteria
**1.** User must be logged in to add a recipe
**2.** Recipes are displayed in the user's library and public feed 
**3.** Recipe form must include: title, caption, ingredients/amounts, steps, image
**4.** Recipe title and slug is unique

---
#### Tasks
- [x] Create Recipe data model
- [x] Create 'Add Recipe' form and style with CSS
- [x] Add form validation
- [x] Link the form to the data model
