### ISSUE TITLE
USER STORY: Account Registration (User)

### ISSUE THREAD

**Issue by BeckySkel** [BeckySkel/fullstack-project-4#6]
As a **user**, I can **create an account** so that **I can interact with other users content and create my own**.

---
#### Acceptance Criteria
**1.** Account details are authenticated with allauth during registration
**2.** User can log in and out of account using link in navbar

---
#### Tasks
- [x] Install and implement allauth to handle user registration
- [x] Style registration and login forms
- [x] Add dynamic login/logout/register link to nav bar
