### ISSUE TITLE
USER STORY: Like and Comment (User)

### ISSUE THREAD

**Issue by BeckySkel** [BeckySkel/fullstack-project-4#9]
As a **recipe viewer**, I can **like and comment on other's recipes** so that **I can share my opinion**.

---
#### Acceptance Criteria
**1.** User must be logged in to like/comment
**2.** User cannot like their own recipes
**3.** Amount of likes and comments are displayed on recipe card
**4.** Comments are displayed at bottom of recipe reading view

---
#### Tasks
- [x] Add like button and link to Recipe data model
- [x] Add comment form and code to display comment on submission
- [x] Add like and comment counters to recipe displays
